name: fsc_cert
description: Docusign + FSC Hackathon -- Good Code 2020
publish_to: 'none'
version: 1.0.0+1
author: Dhruvil Patel (atdhruvilpatel@gmail.com) 

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.7.4
  cupertino_icons: ^0.1.3
  groovin_material_icons: ^1.1.6
  font_awesome_flutter: ^8.5.0
  http: ^0.12.0+2
  json_annotation: ^3.0.1
  url_launcher: ^5.4.10
  shared_preferences: ^0.5.10
  provider: ^4.3.2+1
  intl: ^0.16.1
  flutter_typeahead: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.3
  json_serializable: ^3.2.5
  pedantic: ^1.9.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon_transparent.png"

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf
    - family: HelveticaCondensed
      fonts:
        - asset: assets/fonts/Helvetica-Condensed.ttf